#!/bin/bash
BIN_PATH=../bin/1.2-radar/obpmark-1.2-radar

MULTI_LOOK=4

IMAGE_WIDTH=1728
IMAGE_HEIGHT=8815

${BIN_PATH}_cpu -m $MULTI_LOOK -w $IMAGE_WIDTH -h $IMAGE_HEIGHT -r -t
${BIN_PATH}_openmp -m $MULTI_LOOK -w $IMAGE_WIDTH -h $IMAGE_HEIGHT -r -t
${BIN_PATH}_opencl -m $MULTI_LOOK -w $IMAGE_WIDTH -h $IMAGE_HEIGHT -r -t
${BIN_PATH}_cuda -m $MULTI_LOOK -w $IMAGE_WIDTH -h $IMAGE_HEIGHT -r -t

IMAGE_WIDTH=2752
IMAGE_HEIGHT=14357

${BIN_PATH}_cpu -m $MULTI_LOOK -w $IMAGE_WIDTH -h $IMAGE_HEIGHT -r -t
${BIN_PATH}_openmp -m $MULTI_LOOK -w $IMAGE_WIDTH -h $IMAGE_HEIGHT -r -t
${BIN_PATH}_opencl -m $MULTI_LOOK -w $IMAGE_WIDTH -h $IMAGE_HEIGHT -r -t
${BIN_PATH}_cuda -m $MULTI_LOOK -w $IMAGE_WIDTH -h $IMAGE_HEIGHT -r -t

IMAGE_WIDTH=4800
IMAGE_HEIGHT=24487

${BIN_PATH}_cpu -m $MULTI_LOOK -w $IMAGE_WIDTH -h $IMAGE_HEIGHT -r -t
${BIN_PATH}_openmp -m $MULTI_LOOK -w $IMAGE_WIDTH -h $IMAGE_HEIGHT -r -t
${BIN_PATH}_opencl -m $MULTI_LOOK -w $IMAGE_WIDTH -h $IMAGE_HEIGHT -r -t
${BIN_PATH}_cuda -m $MULTI_LOOK -w $IMAGE_WIDTH -h $IMAGE_HEIGHT -r -t

IMAGE_WIDTH=5616
IMAGE_HEIGHT=28904

${BIN_PATH}_cpu -m $MULTI_LOOK -w $IMAGE_WIDTH -h $IMAGE_HEIGHT -r -t
${BIN_PATH}_openmp -m $MULTI_LOOK -w $IMAGE_WIDTH -h $IMAGE_HEIGHT -r -t
${BIN_PATH}_opencl -m $MULTI_LOOK -w $IMAGE_WIDTH -h $IMAGE_HEIGHT -r -t
${BIN_PATH}_cuda -m $MULTI_LOOK -w $IMAGE_WIDTH -h $IMAGE_HEIGHT -r -t
