# OBPMark top-level Makefile
# Author: david.steenari@esa.int
# Please see LICENSE in the top directory for licensing information. 

MAKEFILES := 1.1-image

1.1-image: 
	$(MAKE) -f $* all

1.2-radar:
	$(MAKE) -f $* all
